import ollama
from ollama import Client
import concurrent.futures

# --- CONFIGURATION ---
PHONE_IP = "192.168.1.15"  # <-- CHANGE THIS TO YOUR PHONE'S IP ADDRESS
PHONE_URL = f"http://{PHONE_IP}:11434"

# We create a specific client to talk to the phone over the Wi-Fi
phone_client = Client(host=PHONE_URL)

def summarize_on_pc(text_chunk):
    """Runs locally on the Master PC using its hardware."""
    print("💻 PC: Starting summarization of Part 1...")
    # Assuming you still have Phi-3 on your PC!
    response = ollama.chat(model="phi3", messages=[
        {'role': 'user', 'content': f"Summarize this text:\n\n{text_chunk}"}
    ])
    print("💻 PC: Finished!")
    return response['message']['content']

def summarize_on_phone(text_chunk):
    """Beams the text over Wi-Fi to the Android phone for processing."""
    print("📱 Phone: Starting summarization of Part 2...")
    try:
        # We use the mobile-friendly Llama model here
        response = phone_client.chat(model="llama3.2:1b", messages=[
            {'role': 'user', 'content': f"Summarize this text:\n\n{text_chunk}"}
        ])
        print("📱 Phone: Finished!")
        return response['message']['content']
    except Exception as e:
        return f"📱 Phone Error: {e}\n(Check if the IP is correct and OLLAMA_HOST=0.0.0.0 is running on Termux)"

def split_text(text):
    """Splits the text roughly in half, trying not to cut a word in half."""
    halfway = len(text) // 2
    # Find the nearest space to the halfway point
    split_point = text.rfind(' ', 0, halfway) 
    if split_point == -1:
        split_point = halfway
        
    part1 = text[:split_point]
    part2 = text[split_point:]
    return part1, part2

def master_job(full_text):
    print("✂️ Splitting document in half...")
    part1, part2 = split_text(full_text)
    
    print("🚀 Distributing tasks to nodes...\n")
    
    # This ThreadPoolExecutor allows both functions to run at the exact same time
    with concurrent.futures.ThreadPoolExecutor() as executor:
        # Submit tasks to the pool
        future_pc = executor.submit(summarize_on_pc, part1)
        future_phone = executor.submit(summarize_on_phone, part2)
        
        # The script will pause here until BOTH devices finish their jobs
        pc_summary = future_pc.result()
        phone_summary = future_phone.result()
        
    # --- Print the Final Combined Output ---
    print("\n" + "="*50)
    print("🎉 COMBINED DISTRIBUTED SUMMARY 🎉")
    print("="*50)
    print("\n--- 💻 PART 1 (Generated by PC) ---")
    print(pc_summary.strip())
    print("\n--- 📱 PART 2 (Generated by Phone) ---")
    print(phone_summary.strip())
    print("="*50)

if __name__ == "__main__":
    # A decently long sample text to split
    sample_text = """
    The history of artificial intelligence (AI) began in antiquity, with myths, stories and rumors 
    of artificial beings endowed with intelligence or consciousness by master craftsmen. The seeds 
    of modern AI were planted by classical philosophers who attempted to describe the process of 
    human thinking as the mechanical manipulation of symbols. This work culminated in the invention 
    of the programmable digital computer in the 1940s, a machine based on the abstract essence of 
    mathematical reasoning. 
    
    This device and the ideas behind it inspired a handful of scientists to begin seriously discussing 
    the possibility of building an electronic brain. The field of AI research was founded at a workshop 
    held on the campus of Dartmouth College during the summer of 1956. Those who attended would become 
    the leaders of AI research for decades. Many of them predicted that a machine as intelligent as a 
    human being would exist in no more than a generation, and they were given millions of dollars to 
    make this vision come true.
    """
    
    master_job(sample_text)